- "Base_findGongDan" # key 存今天所有的小车单 0
- "Base_error_toast_first" # key 记录小车单内字段有问题且已提醒的单id 1
- "Base_error_id" # key 记录小车单内字段有问题不能加入计划的单 2
- "Base_error_toast" # 创建计划时有记录加不进计划的小车单 7
- "Base_all_planId" # 存储当日小车计划id 10
- "Base_error_judge_done" # 存储计划中没有添加系统需要提醒的单 11
- "Base_allPlan" # 判断今天是否建了小车计划 12
- "Base_all_yet_planId" # 昨日小车计划id 16
- "Base_all_warn" # 记录计划中目前所有工单id 18
- {"0526-0601": ["allenzhou", "lilianchen", "allenzou", "princewang", "lucasyang"]} # 每个时期负责小车的员工 21
- "Base_all_content" # 22
- "Base_remind" # 当日小车提醒了测试人员测试为1，否则为0 23
- "Base_all_yet_warn" # 25
- "Base_time_smallCar" # 记录当日时间 26
- "Base_is_judge_back"
- "Base_dan_count" # 记录今日计划有多少单 29
- "Base_apiSelfInfo" # 接口自动化信息 30
- "Base_wholeNetwork" # 记录每天发送全网报告 31
- "Base_num_id" # 发布外灰名单的数量index 33
- "Base_ReadyEvn"
- "Base_PersonOfWeek" # 记录每周的时间和对应的测试、评审人员 20
- 'Base_driver' # 记录发车司机
- 'Base_yPerson' # 昨天的测试、评审、开发司机 22
- 'Base_uiSelfInfo'
- 'Base_runSelf' # 自动化运行tag 24
- 'Base_plan_content' # 存储计划内容 提醒下车回退代码 25
- 'Base_xiaoe_last_archive_time' # 记录全网时间以便计算1h后归档 26
- 'Base_oversea_num_id' # 记录海外发布外灰名单的数量index 27