# 教培小车配置
AllDan: "findGongDan" # key 存今天所有的小车单 0
ColumnErrorToasted: "error_toast_first" # key 记录小车单内字段有问题且已提醒的单id 1
ColumnErrorId: "error_id" # key 记录小车单内字段有问题不能加入计划的单id 2
DanErrorToast: "error_toast" # 创建计划时记录加不进计划已提醒的小车单 3
PlanId: "all_planId" # 存储当日小车计划id 4
NOSystemError: "error_judge_done" # 存储计划中没有添加系统需要提醒的单 5
IsCreatePlan: "allPlan" # 判断今天是否建了小车计划 6
YesterdatPlanId: "all_yet_planId" # 昨日小车计划id 7
AllDanId: "all_warn" # 存储允许全网的小车单Id 8
ReviewPassId: "all_content" # 存储评审通过的小车单ID 10
RemindTest: "qql_remind" # 当日小车提醒了测试人员测试为1，否则为0 11
TodayTime: "time_smallCar" # 记录当日时间 13
DanNum: "dan_count" # 记录计划中小车单状态全为评审通过后的数量 15
ApiInfo: "apiSelfInfo" # 接口自动化信息 16
WholeNetworkReport: "wholeNetwork" # 记录每天发送全网报告 17
OutsideGrayIndex: "num_id" # 发布外灰名单的索引 18
EvnTag: "ReadyEvn" # 19
PersonOfWeek: "PersonOfWeek" # 记录每周的时间和对应的测试、评审人员 20
Driver: 'driver' # 记录发车司机 21
YesterdayPersonofWeek: 'yPerson' # 昨天的测试、评审、开发司机 22
UiInfo: 'uiSelfInfo' # ui自动化信息 23
RunSelfTag: 'runSelf' # 自动化运行tag 24
PlanContent: 'plan_content' # 存储计划内容 提醒下车回退代码 25
LastArchiveTime: 'xiaoe_last_archive_time' # 记录全网时间以便计算1h后归档 26
OverseaGrayIndex: 'oversea_num_id' # 记录海外发布外灰名单的数量index 27