- "Test_findGongDan" # key 存今天所有的小车单 0
- "Test_error_toast_first" # key 记录小车单内字段有问题且已提醒的单id 1
- "Test_error_id" # key 记录小车单内字段有问题不能加入计划的单 2
- "Test_error_toast" # 创建计划时有记录加不进计划的小车单 7
- "Test_all_planId" # 存储当日小车计划id 10
- "Test_error_judge_done" # 存储计划中没有添加系统需要提醒的单 11
- "Test_allPlan" # 判断今天是否建了小车计划 12
- "Test_all_yet_planId" # 昨日小车计划id 16
- "Test_all_warn" # 记录计划中目前所有工单id 18
- {"0526-0601": ["allenzhou", "lilianchen", "allenzou", "princewang", "lucasyang"]} # 每个时期负责小车的员工 21
- "Test_all_content" # 22
- "Test_remind" # 当日小车提醒了测试人员测试为1，否则为0 23
- "Test_all_yet_warn" # 25
- "Test_time_smallCar" # 记录当日时间 26
- "Test_is_judge_back"
- "Test_dan_count" # 记录今日计划有多少单 29
- "Test_apiSelfInfo" # 接口自动化信息 30
- "Test_wholeNetwork" # 记录每天发送全网报告 31
- "Test_num_id" # 发布外灰名单的数量index 33
- "Test_ReadyEvn"
- "Test_PersonOfWeek" # 记录每周的时间和对应的测试、评审人员 20
- 'Test_driver' # 记录发车司机
- 'Test_yPerson' # 昨天的测试、评审、开发司机 22
- 'Test_uiSelfInfo'